version: '3.8'
services:
  backend:
    build:
      context: backend
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
  integration:
    build:
      context: integration
    depends_on:
      - backend
