version: '3.8'
services:
  backend:
    build:
      context: backend
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - SQL_USER=backend
      - SQL_PASSWORD=toor
      - SQL_HOST=db
    depends_on:
      - db
  frontend:
    build:
      context: front
    ports:
      - '3000:3000'
    environment:
      - BLOGAPI=http://backend:8000
    depends_on:
      - backend
  db:
    container_name: db
    build:
      context: db
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_HOST=localhost
  integration:
    build:
      context: integration
    depends_on:
      - backend
      - db
      - frontend
