parserOptions:
  project: true
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:@typescript-eslint/strict"
  - "next/core-web-vitals"
  - "prettier"
plugins:
  - "@typescript-eslint"
root: true
rules:
  "@typescript-eslint/explicit-function-return-type": error
  "@typescript-eslint/no-require-imports": error
  "@typescript-eslint/prefer-readonly": error
  "@typescript-eslint/strict-boolean-expressions": error
  "@typescript-eslint/no-explicit-any": error
  "@typescript-eslint/switch-exhaustiveness-check": error
    - error
    - "argsIgnorePattern": "^_"
  camelcase:
    - error
    - properties: "never"
