name: Push Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pack_backend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      # AWS 認証
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::561712284442:user/web3api
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-1
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr 
      - uses: actions/checkout@v3
      - name: build and push docker image to ecr
        env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: ${{ secrets.FRONTEND_REPO }}
            IMAGE_TAG: ${{ github.sha }}
        run: |
            docker build backend --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
            docker build backend --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
            docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
            docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
  pack_frontend:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

      # AWS 認証
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::561712284442:user/web3api
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - uses: actions/checkout@v3
      - uses: aws-actions/amazon-ecr-login@v1
        id: login-ecr 
      - name: build and push docker image to ecr
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ secrets.BACKEND_REPO }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build front --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker build front --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
