name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pack_backend:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - uses: actions/checkout@v3
    - uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr 
    - name: build and push docker image to ecr
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.FRONTEND_REPO }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build backend --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        docker build backend --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
  pack_frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1
    - uses: actions/checkout@v3
    - uses: aws-actions/amazon-ecr-login@v1
      id: login-ecr 
    - name: build and push docker image to ecr
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: ${{ secrets.BACKEND_REPO }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd backend 
        docker build frontend --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        docker build frontend --tag ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
        docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest
